name: Build and publish nuget packages

on:
    push:
        branches:
        - master
        paths:
        - "**/CHANGELOG.md"
        - ".github/workflows/Build and publish nuget package.yml"
        - "build.fsx"

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100 

    - name: Run build.fsx
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet fsi build.fsx -- -p packages
